### ISSUE TITLE
Shared Properties

### ISSUE THREAD

**Issue by cyouh95** [MinnaTee/prj-rev-bwfs-dasmoto#4]
To avoid repetition in your code, you could specify these shared properties among these elements by using `h2` as the selector:

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/MinnaTee/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Resources/index.css#L21-L41
